alias g git
alias gd 'git diff'
alias gc 'git clean'
alias gdc 'git diff --cached'
alias gco 'git checkout'
alias gre 'git reset'
alias greh 'git reset --hard'
alias gres 'git reset --soft'
alias gcm 'git commit -m'
alias gca 'git commit --amend'
alias gp 'git push'
alias gl 'git pull'
alias glr 'git pull --reabse'
alias gri 'git rebase -i'
alias gst 'git status'
